/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PedidoController;
import javax.swing.ButtonModel;
import model.PizzariaEnum;
import model.PizzasEnum;

/**
 *
 * @author helder
 */
public class TelaTamanhoPizza extends javax.swing.JFrame {

    /**
     * Creates new form TelaTamanhoPizza
     */
    private int linhaSelecionada;
    private int mesaSelecionada;
    private int qtde;

    
    
    public TelaTamanhoPizza() {
        initComponents();
    }
    
    public void setLinhaSelecionada(int linhaSelecionada) {
        this.linhaSelecionada = linhaSelecionada;
    }

    public void setMesaSelecionada(int mesaSelecionada) {
        this.mesaSelecionada = mesaSelecionada;
    }

    public void setQtde(int qtde) {
        this.qtde = qtde;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radGroupTamanhoPizza = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblTamanhoPizza = new javax.swing.JLabel();
        radPequena = new javax.swing.JRadioButton();
        radMedia = new javax.swing.JRadioButton();
        radGrande = new javax.swing.JRadioButton();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        //adiciona os 3 botões ao grupo
        radGroupTamanhoPizza.add(radPequena);
        radGroupTamanhoPizza.add(radMedia);
        radGroupTamanhoPizza.add(radGrande);

        radGroupTamanhoPizza.setSelected((ButtonModel)radPequena, true);

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 51, 51));
        setPreferredSize(new java.awt.Dimension(300, 200));

        lblTamanhoPizza.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblTamanhoPizza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTamanhoPizza.setText("Qual o Tamanho da Pizza?");

        radPequena.setText("Pequena");
        radPequena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPequenaActionPerformed(evt);
            }
        });

        radMedia.setText("Media");
        radMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMediaActionPerformed(evt);
            }
        });

        radGrande.setText("Grande");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTamanhoPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radPequena)
                                .addGap(18, 18, 18)
                                .addComponent(radMedia)
                                .addGap(18, 18, 18)
                                .addComponent(radGrande)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTamanhoPizza)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radPequena)
                    .addComponent(radMedia)
                    .addComponent(radGrande))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnConfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radPequenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPequenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radPequenaActionPerformed

    private void radMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radMediaActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        int tamPizza = 1;
        //verifica qual botão está selecionado
        if(radPequena.isSelected()){
            tamPizza = PizzasEnum.P.getValor;
        }
        else if(radMedia.isSelected()){
            tamPizza = PizzasEnum.M.getValor;
        }
        else{
            tamPizza = PizzasEnum.G.getValor;
        }
        
        PedidoController pedido = new PedidoController();          
        //chama o controlador pra fazer o pedido    
        pedido.adicionaPedido(
                linhaSelecionada,mesaSelecionada, tamPizza, qtde);
        
        dispose();
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTamanhoPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTamanhoPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTamanhoPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTamanhoPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTamanhoPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTamanhoPizza;
    private javax.swing.JRadioButton radGrande;
    private javax.swing.ButtonGroup radGroupTamanhoPizza;
    private javax.swing.JRadioButton radMedia;
    private javax.swing.JRadioButton radPequena;
    // End of variables declaration//GEN-END:variables
}
